### ISSUE TITLE
Disabled states in radio and checkboxes should affect labels

### ISSUE THREAD

**Issue by portomarco** [lightspeed/flame#113]
Hi,
Like it currently is with buttons, disabled states in radio and checkboxes should also affect their respective labels.

The visual cue that indicates the component is disabled becomes more reliable when it is applied to the element as a whole. 

Attached is an example of the current and expected behaviour.

@ls-timothee-clain is going to submit a PR on this issue
Reviewed the case with @maartenafink .
Thanks!

![Slice](https://user-images.githubusercontent.com/8979934/86032500-76dcb500-ba05-11ea-9d85-e925e421eb55.png)

**Comment by glambert** [comment]
Thanks! Looking forward to that contribution :tada:

**Comment by ls-timothee-clain** [comment]
sure @glambert , It should be in this sprint or next one. can't wait to contribute to flame (even though it will be small )

**Comment by glambert** [comment]
Any contribution is a good contribution :+1:
