### ISSUE TITLE
Allow dropdown to also support "top" related positions

### ISSUE THREAD

**Issue by inooid** [lightspeed/flame#30]
## Description
Currently the `DropdownContainer` is pretty opinionated on the position of the dropdown, while I feel like this constraint should be put on the consumer side and not on the library's end. In some situations when placing a dropdown at the bottom of the page/screen or within a limited height container, it might not always be possible to display a menu that's dropping down, but it should show above it instead.

This css makes the component very opinionated on the position of the dropdown (as well as the animation when opening):

https://github.com/lightspeed/flame/blob/524bd381907fe1d7a03519a34b484a5a594d00e3/packages/flame/src/Dropdown/Dropdown.tsx#L29

Design question: Should the chevron be up or down in this case?

## Design/Examples

![image](https://user-images.githubusercontent.com/1291263/67206954-e7611a00-f412-11e9-9cdc-6fbf27c3b1ef.png)

**Comment by alexislightspeed** [comment]
The Dropdown automatically positions the content of the menu above the Dropdown, should the remaining screen height not be sufficient.
https://gfycat.com/tamedimpledgonolek
https://lightspeed-flame.netlify.com/?path=/story/dropdown--story

Is this what you mean?

**Comment by inooid** [comment]
@alexislightspeed Yes, but then not having the dropdown look ugly and squashed on top of the dropdown target. There's also no way to _force_ the dropdown to always be above (because in some cases popper cannot tell whether it has space below the target due to absolute positioning of the target).

**Comment by xdrdak** [comment]
I'll most likely be adding back some way to position things as forcing the dropdown to always be position downwards might be a bit too restrictive. Perhaps a "position" prop in which you can set to either "top" or "bottom".

Gonna be checking this out, but it shouldn't be too bad to do.
