### ISSUE TITLE
Flame next major

### ISSUE THREAD

**Issue by glambert** [lightspeed/flame#49]
## Description

Tracking issue on what's coming for the next major version of Flame packages.

### Deprecated

- `FlameFonts` component from `@lightspeed/flame/Core` will be removed. Instead, use the [link tag](https://github.com/lightspeed/flame#link-fonts) to load fonts. Problem is Next.js `Head` component does not play nice with it and actually removes the `link` after client-side takes over. Fonts won't be changing very frequently so its usefulness is very limited.
- `Group` will either be moved to a separate package `@lightspeed/flame-group` or remain undocumented but kept as an hidden feature in the codebase. See https://github.com/lightspeed/flame/pull/2.

### Deprecated

- Root level css and sass files will be removed, prefer going through the appropriate namespaced folder to get your utility files. See #56.
- The `cr-` namespace will be removed in favour of the `fl-` namespace. See #56.

**Comment by xdrdak** [comment]
FlameTheme should not be removed. It should be FlameFonts

**Comment by glambert** [comment]
> FlameTheme should not be removed. It should be FlameFonts

My bad, updated 😄

**Comment by glambert** [comment]
Flame 2 released, see #99
