### ISSUE TITLE
Add spacing props to Card

### ISSUE THREAD

**Issue by xdrdak** [lightspeed/flame#8]
## Description

The vast majority of components already have the spacing props.

There are a few exceptions to this, like the `<Card>` component. It would be a good idea to add the styled-system properties to this component, since that feels more natural to use than to wrap it with a `Box` or a `Flex`. Not to mention, it simplifies the markup.

**Comment by alexismo** [comment]
Does it make sense to also add `layout` props to `<Card>` ?
